const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Particles,
		C3.Plugins.Sprite,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Plugins.TiledBg,
		C3.Plugins.Audio,
		C3.Plugins.Touch,
		C3.Plugins.Mouse,
		C3.Plugins.Multiplayer,
		C3.Plugins.Internationalization,
		C3.Plugins.LocalStorage,
		C3.Plugins.Eponesh_GameScore,
		C3.Behaviors.Fade,
		C3.Behaviors.Anchor,
		C3.Plugins.Button,
		C3.Behaviors.scrollto,
		C3.Plugins.Photon,
		C3.Plugins.sliderbar,
		C3.Plugins.TextBox,
		C3.Plugins.qrcode,
		C3.Plugins.Arr,
		C3.Plugins.Json,
		C3.Plugins.HTMLElement,
		C3.Plugins.AJAX,
		C3.Plugins.Dictionary,
		C3.Plugins.Browser,
		C3.Plugins.Date,
		C3.Behaviors.Sin,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.AJAX.Acts.SetHeader,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Exps.time,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.ScriptsInEvents.Tetris_Event1_Act29,
		C3.ScriptsInEvents.Tetris_Event2_Act29,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Particles.Cnds.IsSpraying,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Cnds.IsOverlappingOffset,
		C3.Plugins.Sprite.Exps.PickedCount,
		C3.Plugins.Text.Acts.AddInstanceVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Text.Acts.AppendText,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Cnds.IsNaN,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.AJAX.Acts.Post,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Plugins.AJAX.Exps.LastStatusCode,
		C3.ScriptsInEvents.Tetris_Event115_Act12,
		C3.ScriptsInEvents.Tetris_Event117_Act1,
		C3.Plugins.Sprite.Cnds.PickTopBottom,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Eponesh_GameScore.Acts.LeaderboardOpen,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowFullscreen,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowRewarded,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSetName,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSetScore,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSync,
		C3.Plugins.Multiplayer.Cnds.OnPeerMessage,
		C3.Plugins.Multiplayer.Acts.HostBroadcastMessage,
		C3.Plugins.Multiplayer.Exps.FromID,
		C3.Plugins.Multiplayer.Exps.Message,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.System.Acts.SetCanvasSize,
		C3.Plugins.Multiplayer.Acts.SignallingConnect,
		C3.ScriptsInEvents.Menu_Event1_Act1,
		C3.Plugins.Multiplayer.Acts.DisconnectRoom,
		C3.Plugins.Text.Acts.SetInstanceVar,
		C3.Plugins.Arr.Acts.Clear,
		C3.Plugins.Eponesh_GameScore.Exps.DeviceType,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.Json.Exps.ArraySize,
		C3.Plugins.System.Acts.Signal,
		C3.Plugins.System.Cnds.OnSignal,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Dictionary.Cnds.HasKey,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.Dictionary.Acts.AddKey,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Plugins.Date.Exps.Now,
		C3.Plugins.AJAX.Acts.Request,
		C3.Plugins.AJAX.Cnds.OnError,
		C3.Plugins.Eponesh_GameScore.Acts.GameplayStop,
		C3.Plugins.Eponesh_GameScore.Acts.GameplayStart,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsRewardedReward,
		C3.Plugins.Photon.Acts.connect,
		C3.Plugins.Photon.Cnds.onJoinedLobby,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Photon.Cnds.isConnectedToNameServer,
		C3.Plugins.Multiplayer.Acts.AddICEServer,
		C3.Plugins.TextBox.Acts.SetVisible,
		C3.Plugins.TextBox.Acts.SetReadOnly,
		C3.Plugins.Multiplayer.Cnds.SignallingIsConnected,
		C3.Plugins.Eponesh_GameScore.Exps.PlayerName,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.TextBox.Acts.SetCSSStyle,
		C3.Plugins.System.Acts.WaitForSignal,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.Multiplayer.Acts.SignallingDisconnect,
		C3.Plugins.Multiplayer.Acts.SignallingLogin,
		C3.Plugins.System.Exps.len,
		C3.Plugins.Multiplayer.Cnds.OnPeerConnected,
		C3.Plugins.Multiplayer.Exps.ListRoomCount,
		C3.Plugins.Multiplayer.Exps.ErrorMessage,
		C3.Plugins.TextBox.Acts.SetMaxLength,
		C3.Plugins.TextBox.Cnds.OnTextChanged,
		C3.Plugins.TextBox.Acts.SetText,
		C3.Plugins.System.Exps.left,
		C3.Plugins.Multiplayer.Acts.SignallingJoinRoom,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Multiplayer.Acts.SignallingRequestRoomList,
		C3.Plugins.sliderbar.Exps.Value,
		C3.Plugins.Multiplayer.Exps.ListRoomName,
		C3.Plugins.Multiplayer.Exps.CurrentRoom,
		C3.Plugins.Multiplayer.Cnds.SignallingIsInRoom,
		C3.Plugins.Multiplayer.Exps.MyAlias,
		C3.Plugins.Multiplayer.Acts.SignallingAutoJoinRoom,
		C3.Plugins.Multiplayer.Acts.SignallingLeaveRoom,
		C3.Plugins.Multiplayer.Cnds.OnPeerDisconnected,
		C3.Plugins.Multiplayer.Exps.MyID,
		C3.Plugins.Multiplayer.Exps.HostID,
		C3.Plugins.Multiplayer.Acts.SendPeerMessage,
		C3.Plugins.Text.Cnds.CompareText,
		C3.Plugins.TextBox.Acts.AppendText,
		C3.Plugins.TextBox.Acts.ScrollToBottom,
		C3.Plugins.AJAX.Cnds.OnAnyError,
		C3.Plugins.Multiplayer.Exps.FromAlias,
		C3.Plugins.Multiplayer.Exps.PeerID,
		C3.Plugins.Multiplayer.Exps.PeerCount,
		C3.Plugins.Text.Acts.SubInstanceVar,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Multiplayer.Cnds.OnSignallingJoinedRoom,
		C3.Plugins.Multiplayer.Exps.PeerAlias,
		C3.Plugins.Multiplayer.Exps.PeerAliasAt,
		C3.Plugins.Multiplayer.Exps.PeerIDAt,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Plugins.Arr.Cnds.CompareCurrent,
		C3.Plugins.Arr.Exps.CurX,
		C3.Plugins.Multiplayer.Cnds.OnRoomList,
		C3.Plugins.Multiplayer.Exps.ListRoomPeerCount,
		C3.Plugins.Multiplayer.Cnds.OnSignallingLeftRoom,
		C3.Plugins.Multiplayer.Exps.SignallingName,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.Arr.Cnds.Contains,
		C3.Plugins.Arr.Exps.CurY,
		C3.ScriptsInEvents.Tetris3_Event22_Act1,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.Text.Acts.MoveForward,
		C3.ScriptsInEvents.Tetris3_Event360_Act3,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.Multiplayer.Cnds.OnHostDisconnected,
		C3.Plugins.Multiplayer.Exps.HostAlias,
		C3.ScriptsInEvents.Tetris3_Event735_Act1,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.ScriptsInEvents.Gameover_Event1_Act1,
		C3.ScriptsInEvents.Gameover_Event1_Act2,
		C3.Plugins.Arr.Exps.CurValue,
		C3.Plugins.Arr.Acts.Sort,
		C3.Plugins.Arr.Acts.Reverse,
		C3.Plugins.Arr.Cnds.CompareX,
		C3.Plugins.Arr.Acts.JSONDownload,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowSticky,
		C3.Plugins.Text.Acts.SetX,
		C3.Plugins.Text.Exps.X,
		C3.Plugins.Eponesh_GameScore.Acts.GameStart,
		C3.ScriptsInEvents.Tutu2_Event22_Act1,
		C3.ScriptsInEvents.Tetrisshadowevent_Event3_Act3,
		C3.ScriptsInEvents.Tetrisshadowevent_Event4_Act1,
		C3.ScriptsInEvents.Tetrisshadowevent_Event5_Act1,
		C3.ScriptsInEvents.Tetrisshadowevent_Event113_Act1,
		C3.ScriptsInEvents.Tetrisshadowevent_Event113_Act2,
		C3.ScriptsInEvents.Tetrisshadowevent_Event114_Act1,
		C3.ScriptsInEvents.Tetrisshadowevent_Event114_Act2,
		C3.ScriptsInEvents.Tetrisshadowevent_Event115_Act1,
		C3.ScriptsInEvents.Tetrisshadowevent_Event115_Act2,
		C3.ScriptsInEvents.Tetrisshadowevent_Event116_Act1,
		C3.ScriptsInEvents.Tetrisshadowevent_Event116_Act2,
		C3.ScriptsInEvents.Tetrisshadowevent_Event117_Act1,
		C3.ScriptsInEvents.Tetrisshadowevent_Event117_Act2,
		C3.ScriptsInEvents.Tetrisshadowevent_Event118_Act1,
		C3.ScriptsInEvents.Tetrisshadowevent_Event118_Act2,
		C3.ScriptsInEvents.Tetrisshadoweventreal_Event21_Act1,
		C3.ScriptsInEvents.Tetrisshadoweventreal_Event22_Act1,
		C3.ScriptsInEvents.Tetrisshadoweventreal_Event261_Act2,
		C3.ScriptsInEvents.Tetrisshadoweventreal_Event294_Act3
	];
};
self.C3_JsPropNameTable = [
	{Particles1: 0},
	{Particles0: 0},
	{Particles2: 0},
	{Particles3: 0},
	{Particles4: 0},
	{Particles5: 0},
	{Particles6: 0},
	{falling: 0},
	{toMove: 0},
	{Fall_Bricks: 0},
	{nextPiece: 0},
	{createNewPiece: 0},
	{rotateable: 0},
	{revolve: 0},
	{Keyboard: 0},
	{wall: 0},
	{LineIdentifier: 0},
	{lines: 0},
	{txtcount: 0},
	{txtlabel: 0},
	{Brick_Rotate: 0},
	{Rotate_Holder: 0},
	{BG: 0},
	{Audio: 0},
	{спр: 0},
	{Pause: 0},
	{F_534414210_6QcP0uUvXWw2K9HVh1huhW9IyfM3YYMp: 0},
	{PausePoverh: 0},
	{Тач: 0},
	{Мышь: 0},
	{PausePoverh2: 0},
	{episka: 0},
	{txtlabel2: 0},
	{Мультиплеер: 0},
	{vividblurredcolorfulwallpaperbackground_: 0},
	{txtcount2: 0},
	{txtlabel3: 0},
	{БезИм22ени: 0},
	{Спрайт: 0},
	{ОдиночнаяИгра: 0},
	{Спрайт2: 0},
	{Спрайт3: 0},
	{Локализация: 0},
	{ЛокальноеХранилище: 0},
	{GamePush: 0},
	{Угасание: 0},
	{Спрайт4: 0},
	{TapPravo: 0},
	{TapLevo: 0},
	{povernut: 0},
	{pravonorm: 0},
	{RightSthela: 0},
	{ok: 0},
	{levo: 0},
	{levo2: 0},
	{levokhasivo: 0},
	{LeftSthela: 0},
	{povernutinstr: 0},
	{PovernutStrela: 0},
	{Down: 0},
	{niza: 0},
	{POVERNUTBOTTON: 0},
	{POVERNUTBOTTON2: 0},
	{pngwingcom: 0},
	{DOWNBUTTON: 0},
	{DownStrela: 0},
	{klucha2: 0},
	{klavafigur: 0},
	{KlavaInstrumentStrela: 0},
	{idlocal: 0},
	{KAKAKSHKA: 0},
	{rapentasend: 0},
	{txtcount3: 0},
	{polza: 0},
	{polzaobza: 0},
	{polza3: 0},
	{Якорь: 0},
	{bestscore: 0},
	{igratesche: 0},
	{menu: 0},
	{menuglav: 0},
	{tetris: 0},
	{voprosednd: 0},
	{voprostext: 0},
	{voprosknopa: 0},
	{daha: 0},
	{rekla: 0},
	{cirarekli: 0},
	{СледитьЗа: 0},
	{tablicarekov: 0},
	{Photon: 0},
	{Спрайт5: 0},
	{Спрайт6: 0},
	{Pisya: 0},
	{podkluchitsya: 0},
	{svoyakomabutton: 0},
	{obhsayakoma: 0},
	{svoyakomabutton2: 0},
	{igrasdrugom: 0},
	{igrasosluchainmim: 0},
	{kolvospisi: 0},
	{spisaserv: 0},
	{kolvoigrokov: 0},
	{Спрайт7: 0},
	{kakoiserv: 0},
	{Спрайт8: 0},
	{sozdatkomnatu: 0},
	{Ползунок: 0},
	{spisaserv2: 0},
	{Текст: 0},
	{Спрайт9: 0},
	{Текст2: 0},
	{spisaigrokov: 0},
	{spisaigrokov2: 0},
	{ВводТекста: 0},
	{chislo: 0},
	{Текст3: 0},
	{nicka: 0},
	{Текст4: 0},
	{izmenit: 0},
	{Спрайт10: 0},
	{izmenit2: 0},
	{izmenit3: 0},
	{QRкод: 0},
	{ВводТекста2: 0},
	{ВводТекста3: 0},
	{ВводТекста4: 0},
	{ВводТекста5: 0},
	{Текст5: 0},
	{Текст6: 0},
	{spisaserv3: 0},
	{гала: 0},
	{ждатьеще: 0},
	{kolvogolosov: 0},
	{spisaigrokov3: 0},
	{kolvogolos: 0},
	{spisaigrokov4: 0},
	{playername: 0},
	{scores: 0},
	{txtcount4: 0},
	{Текст7: 0},
	{Текст8: 0},
	{Текст9: 0},
	{instrukciy1chat2: 0},
	{Спрайт11: 0},
	{Текст10: 0},
	{klavaawsd: 0},
	{chatatexta: 0},
	{chatpisa: 0},
	{Спрайт12: 0},
	{Спрайт13: 0},
	{otpravit: 0},
	{ВводТекста6: 0},
	{hostvishel: 0},
	{hostvishel2: 0},
	{txtcount5: 0},
	{txtcount6: 0},
	{spisaserv4: 0},
	{soobshastatusa: 0},
	{Массив: 0},
	{Массив2: 0},
	{JSON: 0},
	{HTMLЭлемент: 0},
	{Текст11: 0},
	{Кнопка: 0},
	{Спрайт14: 0},
	{Спрайт15: 0},
	{Спрайт16: 0},
	{Спрайт17: 0},
	{Спрайт18: 0},
	{Спрайт19: 0},
	{Спрайт20: 0},
	{AJAX: 0},
	{JSON2: 0},
	{Словарь: 0},
	{Текст12: 0},
	{Спрайт21: 0},
	{Кнопка2: 0},
	{Текст13: 0},
	{Кнопка3: 0},
	{Кнопка4: 0},
	{Кнопка5: 0},
	{Массив3: 0},
	{Массив4: 0},
	{Текст14: 0},
	{Текст15: 0},
	{среднерога16отладка: 0},
	{Кнопка6: 0},
	{МассивДЛяВышвырнутых: 0},
	{JSON3: 0},
	{МассивПросивших: 0},
	{voprosednd2: 0},
	{Кнопка7: 0},
	{igranzanovo: 0},
	{pererzaitivkomu: 0},
	{pererzaitivkomu2: 0},
	{Спрайт22: 0},
	{Спрайт23: 0},
	{Спрайт24: 0},
	{Браузер: 0},
	{Спрайт25: 0},
	{wall2: 0},
	{Спрайт26: 0},
	{domik: 0},
	{domik2: 0},
	{igranzanovo2: 0},
	{igrappgntextt: 0},
	{Массивbazaidsisya: 0},
	{Дата: 0},
	{среднерога16отладка2: 0},
	{Словарь2: 0},
	{ten: 0},
	{Словарь3: 0},
	{КнопаИграть: 0},
	{playka: 0},
	{podkluchitsya2: 0},
	{podkl: 0},
	{МассивДляЗаписи: 0},
	{СловарьДляПоиска: 0},
	{МассивСыгранногоИгрока: 0},
	{obshayakomaa: 0},
	{обша: 0},
	{obshayagreen: 0},
	{igrasosluchainmim2: 0},
	{voprosednd3: 0},
	{Текст16: 0},
	{Синусоида: 0},
	{voprostext2: 0},
	{posmotret: 0},
	{tablicarekov2: 0},
	{tablicarekovv: 0},
	{Family1: 0},
	{explosion: 0},
	{pause1: 0},
	{pauseonoff: 0},
	{dlyatexa: 0},
	{score: 0},
	{SKOLKOBILO: 0},
	{"2SKOLKOBILO": 0},
	{RAZNICA: 0},
	{INSTRUKCIUNADO: 0},
	{GAMEOVER: 0},
	{PEREMENNAYABEST: 0},
	{PENUHA: 0},
	{SENUHA: 0},
	{REKLAMAMOZHNO: 0},
	{PRYAMREKLA: 0},
	{MOZHNOSEKI: 0},
	{SUPERPISYA: 0},
	{playerNumericId: 0},
	{GAME_MODE_ID: 0},
	{vina: 0},
	{startTime: 0},
	{KNOPKAOKNENAZHATA: 0},
	{hit: 0},
	{DAMOZHNOSOHRANYAT: 0},
	{pause2: 0},
	{pauseonoff2: 0},
	{dlyatexa2: 0},
	{pause3: 0},
	{pauseonoff3: 0},
	{dlyatexa3: 0},
	{score2: 0},
	{SKOLKOBILO2: 0},
	{"2SKOLKOBILO2": 0},
	{RAZNICA2: 0},
	{MENUHA: 0},
	{devicetype: 0},
	{bazaid: 0},
	{zakagotova34: 0},
	{hasplayed: 0},
	{lastgametime: 0},
	{lastgametime2: 0},
	{lastchecktime: 0},
	{checktime: 0},
	{yasigralkatu: 0},
	{yasigralkatu2: 0},
	{snachalazashel: 0},
	{mozhnozagruz: 0},
	{yazagruzilposlekati: 0},
	{yasigraluzhevetoi: 0},
	{modes: 0},
	{modes2: 0},
	{lastreklama: 0},
	{lastmenu: 0},
	{posmotrelrewardu: 0},
	{total: 0},
	{iLoop: 0},
	{VictoryCount: 0},
	{pause4: 0},
	{pauseonoff4: 0},
	{dlyatexa4: 0},
	{score3: 0},
	{SKOLKOBILO3: 0},
	{"2SKOLKOBILO3": 0},
	{RAZNICA3: 0},
	{MENUHA2: 0},
	{nick: 0},
	{perepodkl: 0},
	{mozhet34: 0},
	{zapreta: 0},
	{signalaest: 0},
	{mozhnoajaxotrapv: 0},
	{prishelajaxnicki: 0},
	{hasStar: 0},
	{mozhnoizmenit: 0},
	{vvedeniynick: 0},
	{skokaigrokov: 0},
	{listroomcount: 0},
	{skokaigrokov2: 0},
	{listroomcount2: 0},
	{vklpodozha: 0},
	{vklika: 0},
	{mozhnnomu: 0},
	{kolvovkome: 0},
	{dlyasvoeikomi: 0},
	{odnahaza: 0},
	{knopimozhnogolosov: 0},
	{myroom: 0},
	{sravna: 0},
	{othosta: 0},
	{hvatitprovera2: 0},
	{hvatitprovera3: 0},
	{hvatitprovera4: 0},
	{hvatitprovera5: 0},
	{hvatitprovera6: 0},
	{otkluchennik: 0},
	{YaGotov: 0},
	{forspam: 0},
	{warning: 0},
	{vipolneno: 0},
	{neigraut: 0},
	{igraut: 0},
	{maxpeerkolvovkome: 0},
	{bestroomplayers: 0},
	{bestroomname: 0},
	{StaryiNika: 0},
	{pisu: 0},
	{helpthepoorish: 0},
	{pravilosecundi: 0},
	{peryaptogra: 0},
	{konubok34: 0},
	{nospam: 0},
	{mozhnopis: 0},
	{auzhezahodit: 0},
	{kolvogolosovza2: 0},
	{kolvogolosovprotiv2: 0},
	{zhdems: 0},
	{uzhegolosovalzazhdat: 0},
	{uzhegolosovalzashas: 0},
	{kolvovkomemozhet: 0},
	{uzhedolzhnobitnachatsa: 0},
	{uzheigraemept: 0},
	{zahoda2: 0},
	{prishasoobhNEszahod: 0},
	{nampeshiya: 0},
	{nickhostanapervom: 0},
	{nickhostanapervom2: 0},
	{dahostiku: 0},
	{votp: 0},
	{vrublenopodhuuba: 0},
	{otpravlennaya: 0},
	{poluchkupoluchil: 0},
	{nazhal: 0},
	{nazvakomivkoroibil: 0},
	{fff: 0},
	{pause6: 0},
	{pauseonoff6: 0},
	{dlyatexa6: 0},
	{score5: 0},
	{SKOLKOBILO5: 0},
	{"2SKOLKOBILO5": 0},
	{RAZNICA5: 0},
	{INSTRUKCIUNADO2: 0},
	{GAMEOVER2: 0},
	{bestscore2: 0},
	{PEREMENNAYABEST2: 0},
	{PENUHA2: 0},
	{SENUHA2: 0},
	{rekla2: 0},
	{REKLAMAMOZHNO2: 0},
	{PRYAMREKLA2: 0},
	{MOZHNOSEKI2: 0},
	{SUPERPISYA2: 0},
	{KNOPKAOKNENAZHATA2: 0},
	{DAMOZHNOSOHRANYAT3: 0},
	{pause7: 0},
	{pauseonoff7: 0},
	{dlyatexa7: 0},
	{score6: 0},
	{SKOLKOBILO6: 0},
	{"2SKOLKOBILO6": 0},
	{RAZNICA6: 0},
	{INSTRUKCIUNADO4: 0},
	{GAMEOVER4: 0},
	{bestscore4: 0},
	{PEREMENNAYABEST4: 0},
	{PENUHA4: 0},
	{SENUHA4: 0},
	{rekla4: 0},
	{REKLAMAMOZHNO4: 0},
	{PRYAMREKLA4: 0},
	{MOZHNOSEKI4: 0},
	{SUPERPISYA4: 0},
	{sravnaochi: 0},
	{yes2message: 0},
	{yes2message2: 0},
	{yes3message: 0},
	{yes4message: 0},
	{yes5message: 0},
	{yes6message: 0},
	{yes6message2: 0},
	{yes7message: 0},
	{yes2messagename: 0},
	{yes2message2name: 0},
	{yes3messagename: 0},
	{yes4messagename: 0},
	{yes5messagename: 0},
	{yes6messagename: 0},
	{yes6message2name: 0},
	{yes7messagename: 0},
	{persrandom: 0},
	{kolvovkomedlyazahoda: 0},
	{kolvovkomedlyazahoda2: 0},
	{kolvoyanachal: 0},
	{mozhnosignalku: 0},
	{nicknahoste: 0},
	{podruba: 0},
	{poslepereboya: 0},
	{nadopokazreklu: 0},
	{krasnuha2: 0},
	{krasnuha3: 0},
	{krasnuha4: 0},
	{krasnuha5: 0},
	{krasnuha6: 0},
	{krasnuha7: 0},
	{viha2: 0},
	{viha3: 0},
	{viha4: 0},
	{viha5: 0},
	{viha6: 0},
	{viha7: 0},
	{shishzanyat: 0},
	{moyaaidiha: 0},
	{otklcuhpotomuchtoigrnachtok: 0},
	{na10: 0},
	{zapuskamaki: 0},
	{KNOPKAOKNENAZHATA3: 0},
	{DAMOZHNOSOHRANYAT2: 0},
	{nedoigra: 0},
	{timerdovihi: 0},
	{timerdovihi2: 0},
	{otkluchhost: 0},
	{posleperehosta: 0},
	{dohosta2: 0},
	{viha: 0},
	{vihappizd: 0},
	{vihappizd2: 0},
	{eslireal1: 0},
	{vihappizdnutiy: 0},
	{muzha1: 0},
	{muzha2: 0},
	{muzha3: 0},
	{muzha4: 0},
	{muzha5: 0},
	{muzha6: 0},
	{muzha7: 0},
	{podklaserviza: 0},
	{podklaserviza2: 0},
	{mozhnokrasnuhu: 0},
	{prishlodebil: 0},
	{timerEndTimeIgroka: 0},
	{pause5: 0},
	{pauseonoff5: 0},
	{dlyatexa5: 0},
	{score4: 0},
	{SKOLKOBILO4: 0},
	{"2SKOLKOBILO4": 0},
	{RAZNICA4: 0},
	{INSTRUKCIUNADO3: 0},
	{GAMEOVER3: 0},
	{bestscore3: 0},
	{PEREMENNAYABEST3: 0},
	{PENUHA3: 0},
	{SENUHA3: 0},
	{rekla3: 0},
	{REKLAMAMOZHNO3: 0},
	{PRYAMREKLA3: 0},
	{MOZHNOSEKI3: 0},
	{SUPERPISYA3: 0},
	{KNOPKAOKNENAZHATA4: 0},
	{massivkonaheal: 0},
	{gameoverschet: 0},
	{skok4el: 0},
	{doigraliigru: 0},
	{ustanovlenobazaid: 0},
	{vibrannoepirov: 0},
	{sozdalideri: 0},
	{pozihimP: 0},
	{otpravilzapru: 0},
	{prishloblya: 0},
	{blyyyadneotpravlyallya: 0},
	{chelnesdoh: 0},
	{otpravilsyka: 0},
	{prosivshii: 0},
	{json: 0},
	{gotovielobby: 0},
	{zanyatoshishom: 0},
	{spasibo: 0},
	{invert: 0},
	{Perya1: 0},
	{sorta: 0},
	{EsliMen: 0},
	{Predporta: 0},
	{Predporta2: 0},
	{Pehebohastarta: 0},
	{Pehebohastarta2: 0},
	{Pehebohastarta3: 0},
	{Pehebohastarta4: 0},
	{Pehebohastarta5: 0},
	{massivkona: 0},
	{abebesn: 0},
	{SchetNulei: 0},
	{meunbglav: 0},
	{lastmenu2: 0},
	{gameoverschet2: 0},
	{skok4el2: 0},
	{doigraliigru2: 0},
	{ustanovlenobazaid2: 0},
	{prishlo: 0},
	{proverithochu: 0},
	{proveraserva: 0},
	{temp: 0},
	{nazhataknopaornet: 0},
	{checknutayahooma: 0},
	{checkedrooms: 0},
	{knopanazhatanaten: 0},
	{peryapt: 0},
	{helpthepoor: 0},
	{helpthepoor2: 0},
	{ppizd: 0},
	{helpthepoor3: 0},
	{helpthepoor4: 0},
	{shadowOpponentFound: 0},
	{OpponentId: 0},
	{OpponentName: 0},
	{OpponentScoreJSON: 0},
	{ParsedOpponentArray: 0},
	{отладка: 0},
	{ResizeArrayX: 0},
	{ResizeArrayY: 0},
	{ResizeArrayZ: 0},
	{FlagResizeArray: 0},
	{pause8: 0},
	{pauseonoff8: 0},
	{dlyatexa8: 0},
	{score7: 0},
	{SKOLKOBILO7: 0},
	{"2SKOLKOBILO7": 0},
	{RAZNICA7: 0},
	{INSTRUKCIUNADO5: 0},
	{GAMEOVER5: 0},
	{bestscore5: 0},
	{PEREMENNAYABEST5: 0},
	{PENUHA5: 0},
	{SENUHA5: 0},
	{rekla5: 0},
	{REKLAMAMOZHNO5: 0},
	{PRYAMREKLA5: 0},
	{MOZHNOSEKI5: 0},
	{SUPERPISYA5: 0},
	{KNOPKAOKNENAZHATA5: 0},
	{DAMOZHNOSOHRANYAT4: 0},
	{pause9: 0},
	{pauseonoff9: 0},
	{dlyatexa9: 0},
	{score8: 0},
	{SKOLKOBILO8: 0},
	{"2SKOLKOBILO8": 0},
	{RAZNICA8: 0},
	{INSTRUKCIUNADO6: 0},
	{GAMEOVER6: 0},
	{bestscore6: 0},
	{PEREMENNAYABEST6: 0},
	{PENUHA6: 0},
	{SENUHA6: 0},
	{rekla6: 0},
	{REKLAMAMOZHNO6: 0},
	{PRYAMREKLA6: 0},
	{MOZHNOSEKI6: 0},
	{SUPERPISYA6: 0},
	{sravnaochi2: 0},
	{yes2message3: 0},
	{yes2message4: 0},
	{yes3message2: 0},
	{yes4message2: 0},
	{yes5message2: 0},
	{yes6message3: 0},
	{yes6message4: 0},
	{yes7message2: 0},
	{yes2messagename2: 0},
	{yes2message2name2: 0},
	{yes3messagename2: 0},
	{yes4messagename2: 0},
	{yes5messagename2: 0},
	{yes6messagename2: 0},
	{yes6message2name2: 0},
	{yes7messagename2: 0},
	{persrandom2: 0},
	{kolvovkomedlyazahoda3: 0},
	{kolvovkomedlyazahoda4: 0},
	{kolvoyanachal2: 0},
	{mozhnosignalku2: 0},
	{nicknahoste2: 0},
	{podruba2: 0},
	{poslepereboya2: 0},
	{nadopokazreklu2: 0},
	{krasnuha8: 0},
	{krasnuha9: 0},
	{krasnuha10: 0},
	{krasnuha11: 0},
	{krasnuha12: 0},
	{krasnuha13: 0},
	{viha8: 0},
	{viha9: 0},
	{viha10: 0},
	{viha11: 0},
	{viha12: 0},
	{viha13: 0},
	{shishzanyat2: 0},
	{moyaaidiha2: 0},
	{otklcuhpotomuchtoigrnachtok2: 0},
	{opponentScore: 0},
	{opponentFinished: 0},
	{opponentUpdateSignal: 0},
	{posleshadow: 0},
	{na11: 0},
	{zapuskamaki2: 0},
	{KNOPKAOKNENAZHATA6: 0},
	{DAMOZHNOSOHRANYAT5: 0},
	{nadotpravitaju: 0},
	{sdelalkill: 0},
	{nedoigra2: 0},
	{timerdovihi3: 0},
	{timerdovihi4: 0},
	{prishlodebil2: 0},
	{timerEndTimeIgroka2: 0},
	{massivkonaheal2: 0},
	{gameoverschet3: 0},
	{skok4el3: 0},
	{doigraliigru3: 0},
	{ustanovlenobazaid3: 0},
	{vibrannoepirov2: 0},
	{sozdalideri2: 0},
	{pozihimP2: 0},
	{otpravilzapru2: 0},
	{prishloblya2: 0},
	{blyyyadneotpravlyallya2: 0},
	{chelnesdoh2: 0},
	{otpravilsyka2: 0},
	{prosivshii2: 0},
	{json2: 0},
	{gotovielobby2: 0},
	{zanyatoshishom2: 0},
	{spasibo2: 0},
	{Pehebohastarta6: 0},
	{Pehebohastarta7: 0},
	{Pehebohastarta8: 0},
	{Pehebohastarta9: 0},
	{Pehebohastarta10: 0},
	{massivkona2: 0},
	{abebesn2: 0},
	{SchetNulei2: 0},
	{meunbglav2: 0},
	{lastmenu3: 0}
];

self.InstanceType = {
	Particles1: class extends self.IParticlesInstance {},
	Particles0: class extends self.IParticlesInstance {},
	Particles2: class extends self.IParticlesInstance {},
	Particles3: class extends self.IParticlesInstance {},
	Particles4: class extends self.IParticlesInstance {},
	Particles5: class extends self.IParticlesInstance {},
	Particles6: class extends self.IParticlesInstance {},
	Fall_Bricks: class extends self.ISpriteInstance {},
	revolve: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	wall: class extends self.ISpriteInstance {},
	LineIdentifier: class extends self.ISpriteInstance {},
	txtcount: class extends self.ITextInstance {},
	txtlabel: class extends self.ITextInstance {},
	Brick_Rotate: class extends self.ISpriteInstance {},
	Rotate_Holder: class extends self.ISpriteInstance {},
	BG: class extends self.ITiledBackgroundInstance {},
	Audio: class extends self.IInstance {},
	спр: class extends self.ISpriteInstance {},
	Pause: class extends self.ITextInstance {},
	F_534414210_6QcP0uUvXWw2K9HVh1huhW9IyfM3YYMp: class extends self.ISpriteInstance {},
	PausePoverh: class extends self.ISpriteInstance {},
	Тач: class extends self.IInstance {},
	Мышь: class extends self.IInstance {},
	PausePoverh2: class extends self.ISpriteInstance {},
	episka: class extends self.ITextInstance {},
	txtlabel2: class extends self.ITextInstance {},
	Мультиплеер: class extends self.IInstance {},
	vividblurredcolorfulwallpaperbackground_: class extends self.ISpriteInstance {},
	txtcount2: class extends self.ITextInstance {},
	txtlabel3: class extends self.ITextInstance {},
	БезИм22ени: class extends self.ISpriteInstance {},
	Спрайт: class extends self.ISpriteInstance {},
	ОдиночнаяИгра: class extends self.ISpriteInstance {},
	Спрайт2: class extends self.ISpriteInstance {},
	Спрайт3: class extends self.ISpriteInstance {},
	Локализация: class extends self.IInstance {},
	ЛокальноеХранилище: class extends self.IInstance {},
	GamePush: class extends self.IInstance {},
	Спрайт4: class extends self.ISpriteInstance {},
	TapPravo: class extends self.ISpriteInstance {},
	TapLevo: class extends self.ISpriteInstance {},
	povernut: class extends self.ISpriteInstance {},
	pravonorm: class extends self.ISpriteInstance {},
	RightSthela: class extends self.ISpriteInstance {},
	ok: class extends self.ISpriteInstance {},
	levo: class extends self.ISpriteInstance {},
	levo2: class extends self.ISpriteInstance {},
	levokhasivo: class extends self.ISpriteInstance {},
	LeftSthela: class extends self.ISpriteInstance {},
	povernutinstr: class extends self.ISpriteInstance {},
	PovernutStrela: class extends self.ISpriteInstance {},
	Down: class extends self.ISpriteInstance {},
	niza: class extends self.ISpriteInstance {},
	POVERNUTBOTTON: class extends self.ISpriteInstance {},
	POVERNUTBOTTON2: class extends self.ISpriteInstance {},
	pngwingcom: class extends self.ISpriteInstance {},
	DOWNBUTTON: class extends self.ISpriteInstance {},
	DownStrela: class extends self.ISpriteInstance {},
	klucha2: class extends self.ISpriteInstance {},
	klavafigur: class extends self.ISpriteInstance {},
	KlavaInstrumentStrela: class extends self.ISpriteInstance {},
	idlocal: class extends self.ITextInstance {},
	KAKAKSHKA: class extends self.ITextInstance {},
	rapentasend: class extends self.ISpriteInstance {},
	txtcount3: class extends self.ITextInstance {},
	polza: class extends self.ITextInstance {},
	polzaobza: class extends self.ITextInstance {},
	polza3: class extends self.ITextInstance {},
	bestscore: class extends self.ITextInstance {},
	igratesche: class extends self.ISpriteInstance {},
	menu: class extends self.ISpriteInstance {},
	menuglav: class extends self.ISpriteInstance {},
	voprosednd: class extends self.ISpriteInstance {},
	voprostext: class extends self.ITextInstance {},
	voprosknopa: class extends self.ISpriteInstance {},
	daha: class extends self.ISpriteInstance {},
	rekla: class extends self.IButtonInstance {},
	cirarekli: class extends self.ITextInstance {},
	tablicarekov: class extends self.ISpriteInstance {},
	Photon: class extends self.IInstance {},
	Спрайт5: class extends self.ISpriteInstance {},
	Спрайт6: class extends self.ISpriteInstance {},
	Pisya: class extends self.ITextInstance {},
	podkluchitsya: class extends self.ISpriteInstance {},
	svoyakomabutton: class extends self.ISpriteInstance {},
	obhsayakoma: class extends self.ISpriteInstance {},
	svoyakomabutton2: class extends self.ISpriteInstance {},
	igrasdrugom: class extends self.ISpriteInstance {},
	igrasosluchainmim: class extends self.ISpriteInstance {},
	spisaserv: class extends self.ITextInstance {},
	Спрайт7: class extends self.ISpriteInstance {},
	Спрайт8: class extends self.ISpriteInstance {},
	sozdatkomnatu: class extends self.ISpriteInstance {},
	Ползунок: class extends self.ISliderBarInstance {},
	spisaserv2: class extends self.ITextInstance {},
	Текст: class extends self.ITextInstance {},
	Спрайт9: class extends self.ISpriteInstance {},
	Текст2: class extends self.ITextInstance {},
	spisaigrokov: class extends self.ITextInstance {},
	spisaigrokov2: class extends self.ITextInstance {},
	ВводТекста: class extends self.ITextInputInstance {},
	Текст3: class extends self.ITextInstance {},
	Текст4: class extends self.ITextInstance {},
	izmenit: class extends self.ISpriteInstance {},
	Спрайт10: class extends self.ISpriteInstance {},
	izmenit2: class extends self.ISpriteInstance {},
	izmenit3: class extends self.ISpriteInstance {},
	QRкод: class extends self.IQRCodeInstance {},
	ВводТекста2: class extends self.ITextInputInstance {},
	ВводТекста3: class extends self.ITextInputInstance {},
	ВводТекста4: class extends self.ITextInputInstance {},
	ВводТекста5: class extends self.ITextInputInstance {},
	Текст5: class extends self.ITextInstance {},
	Текст6: class extends self.ITextInstance {},
	spisaserv3: class extends self.ITextInstance {},
	гала: class extends self.ISpriteInstance {},
	ждатьеще: class extends self.ISpriteInstance {},
	spisaigrokov3: class extends self.ITextInstance {},
	spisaigrokov4: class extends self.ITextInstance {},
	txtcount4: class extends self.ITextInstance {},
	Текст7: class extends self.ITextInstance {},
	Текст8: class extends self.ITextInstance {},
	Текст9: class extends self.ITextInstance {},
	Спрайт11: class extends self.ISpriteInstance {},
	Текст10: class extends self.ITextInstance {},
	klavaawsd: class extends self.ISpriteInstance {},
	chatatexta: class extends self.ITextInstance {},
	chatpisa: class extends self.ITextInstance {},
	Спрайт12: class extends self.ISpriteInstance {},
	Спрайт13: class extends self.ISpriteInstance {},
	otpravit: class extends self.ISpriteInstance {},
	ВводТекста6: class extends self.ITextInputInstance {},
	hostvishel: class extends self.ITextInstance {},
	hostvishel2: class extends self.ITextInstance {},
	txtcount5: class extends self.ITextInstance {},
	txtcount6: class extends self.ITextInstance {},
	spisaserv4: class extends self.ITextInstance {},
	soobshastatusa: class extends self.ITextInstance {},
	Массив: class extends self.IArrayInstance {},
	Массив2: class extends self.IArrayInstance {},
	JSON: class extends self.IJSONInstance {},
	HTMLЭлемент: class extends self.IHTMLElementInstance {},
	Текст11: class extends self.ITextInstance {},
	Кнопка: class extends self.IButtonInstance {},
	Спрайт14: class extends self.ISpriteInstance {},
	Спрайт15: class extends self.ISpriteInstance {},
	Спрайт16: class extends self.ISpriteInstance {},
	Спрайт17: class extends self.ISpriteInstance {},
	Спрайт18: class extends self.ISpriteInstance {},
	Спрайт19: class extends self.ISpriteInstance {},
	Спрайт20: class extends self.ISpriteInstance {},
	AJAX: class extends self.IInstance {},
	JSON2: class extends self.IJSONInstance {},
	Словарь: class extends self.IDictionaryInstance {},
	Текст12: class extends self.ITextInstance {},
	Спрайт21: class extends self.ISpriteInstance {},
	Кнопка2: class extends self.IButtonInstance {},
	Текст13: class extends self.ITextInstance {},
	Кнопка3: class extends self.IButtonInstance {},
	Кнопка4: class extends self.IButtonInstance {},
	Кнопка5: class extends self.IButtonInstance {},
	Массив3: class extends self.IArrayInstance {},
	Массив4: class extends self.IArrayInstance {},
	Текст14: class extends self.ITextInstance {},
	Текст15: class extends self.ITextInstance {},
	среднерога16отладка: class extends self.ITextInstance {},
	Кнопка6: class extends self.IButtonInstance {},
	МассивДЛяВышвырнутых: class extends self.IArrayInstance {},
	JSON3: class extends self.IJSONInstance {},
	МассивПросивших: class extends self.IArrayInstance {},
	voprosednd2: class extends self.ISpriteInstance {},
	Кнопка7: class extends self.IButtonInstance {},
	igranzanovo: class extends self.ISpriteInstance {},
	pererzaitivkomu: class extends self.ISpriteInstance {},
	pererzaitivkomu2: class extends self.ISpriteInstance {},
	Спрайт22: class extends self.ISpriteInstance {},
	Спрайт23: class extends self.ISpriteInstance {},
	Спрайт24: class extends self.ISpriteInstance {},
	Браузер: class extends self.IInstance {},
	Спрайт25: class extends self.ISpriteInstance {},
	wall2: class extends self.ISpriteInstance {},
	Спрайт26: class extends self.ISpriteInstance {},
	domik: class extends self.ISpriteInstance {},
	domik2: class extends self.ISpriteInstance {},
	igranzanovo2: class extends self.ISpriteInstance {},
	igrappgntextt: class extends self.ISpriteInstance {},
	Массивbazaidsisya: class extends self.IArrayInstance {},
	Дата: class extends self.IInstance {},
	среднерога16отладка2: class extends self.ITextInstance {},
	Словарь2: class extends self.IDictionaryInstance {},
	ten: class extends self.ISpriteInstance {},
	Словарь3: class extends self.IDictionaryInstance {},
	КнопаИграть: class extends self.ISpriteInstance {},
	playka: class extends self.ISpriteInstance {},
	podkluchitsya2: class extends self.ISpriteInstance {},
	podkl: class extends self.ISpriteInstance {},
	МассивДляЗаписи: class extends self.IArrayInstance {},
	СловарьДляПоиска: class extends self.IDictionaryInstance {},
	МассивСыгранногоИгрока: class extends self.IArrayInstance {},
	obshayakomaa: class extends self.ISpriteInstance {},
	обша: class extends self.ISpriteInstance {},
	obshayagreen: class extends self.ISpriteInstance {},
	igrasosluchainmim2: class extends self.ISpriteInstance {},
	voprosednd3: class extends self.ISpriteInstance {},
	Текст16: class extends self.ITextInstance {},
	voprostext2: class extends self.ITextInstance {},
	posmotret: class extends self.ISpriteInstance {},
	tablicarekov2: class extends self.ISpriteInstance {},
	tablicarekovv: class extends self.ISpriteInstance {},
	Family1: class extends self.ISpriteInstance {},
	explosion: class extends self.IParticlesInstance {}
}